repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive]
  - repo: local
    hooks:
    -   id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: pipenv run test
        language: system
        pass_filenames: false
        always_run: true